version: "3.8"

services:
  algorithm:
    container_name: algorithm
    build:
      context: .
      dockerfile: docker/Dockerfile
    tty: true
    env_file:
      - .env
    volumes:
      - ./workspace/src:/workspace/src
